// <auto-generated />
using Esuper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Esuper.Data.Migrations
{
    [DbContext(typeof(BankDBContext))]
    partial class BankDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Esuper.Data.Model.Transaction", b =>
                {
                    b.Property<int>("transactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("accountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("narration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("transactionID");

                    b.ToTable("BankTransactions");

                    b.HasData(
                        new
                        {
                            transactionID = 1,
                            accountNumber = 59685221L,
                            amount = 100,
                            balance = 100,
                            date = "1/07/2022",
                            narration = "deposit"
                        },
                        new
                        {
                            transactionID = 3,
                            accountNumber = 86322156L,
                            amount = 300,
                            balance = 300,
                            date = "3/07/2022",
                            narration = "deposit"
                        },
                        new
                        {
                            transactionID = 4,
                            accountNumber = 59685221L,
                            amount = 200,
                            balance = 300,
                            date = "4/07/2022",
                            narration = "interest"
                        },
                        new
                        {
                            transactionID = 5,
                            accountNumber = 68525896L,
                            amount = 100,
                            balance = 200,
                            date = "5/07/2022",
                            narration = "transfer in"
                        },
                        new
                        {
                            transactionID = 6,
                            accountNumber = 86322156L,
                            amount = 100,
                            balance = 400,
                            date = "6/07/2022",
                            narration = "salary"
                        },
                        new
                        {
                            transactionID = 7,
                            accountNumber = 59685221L,
                            amount = -50,
                            balance = 250,
                            date = "7/07/2022",
                            narration = "withdrawl"
                        },
                        new
                        {
                            transactionID = 8,
                            accountNumber = 68525896L,
                            amount = -20,
                            balance = 200,
                            date = "8/07/2022",
                            narration = "bank charge"
                        },
                        new
                        {
                            transactionID = 10,
                            accountNumber = 59685221L,
                            amount = -100,
                            balance = 150,
                            date = "10/07/2022",
                            narration = "withdrawl"
                        },
                        new
                        {
                            transactionID = 11,
                            accountNumber = 68525896L,
                            amount = -100,
                            balance = 200,
                            date = "11/07/2022",
                            narration = "eftpos payment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
